import type { AnimalType, Brand, Category, Post, Product } from "@/types/catalogue";

export const animalTypes: AnimalType[] = [
  { id: "animal-dog", name: "Chó", slug: "cho", description: "Sản phẩm chăm sóc và hỗ trợ sức khỏe cho chó.", image: "/images/demo/animal-dogs.jpg" },
  { id: "animal-cat", name: "Mèo", slug: "meo", description: "Sản phẩm dành cho nhu cầu chăm sóc mèo.", image: "/images/demo/animal-cats.jpg" },
  { id: "animal-livestock", name: "Gia súc", slug: "gia-suc", description: "Danh mục tham khảo cho trâu, bò, dê, cừu và heo.", image: "/images/demo/animal-livestock-cattle.jpg" },
  { id: "animal-poultry", name: "Gia cầm", slug: "gia-cam", description: "Sản phẩm tham khảo cho gà, vịt và các nhóm gia cầm.", image: "/images/demo/animal-poultry.jpg" },
  { id: "animal-aquaculture", name: "Thuỷ sản", slug: "thuy-san", description: "Sản phẩm hỗ trợ nuôi trồng thuỷ sản và quản lý môi trường nước.", image: "/images/demo/animal-aquaculture.jpg" },
  { id: "animal-equipment", name: "Thiết bị thú y", slug: "thiet-bi-thu-y", description: "Dụng cụ, vật tư và thiết bị phục vụ chăm sóc thú y.", image: "/images/products/demo-veterinary-syringe.svg" },
];

export const categories: Category[] = [
  { id: "cat-medicine", name: "Thuốc thú y", slug: "thuoc-thu-y", kind: "product_type", description: "Catalogue thuốc thú y theo thông tin do nhà cung cấp xác nhận." },
  { id: "cat-vaccine", name: "Vaccine và sinh phẩm", slug: "vaccine-sinh-pham", kind: "product_type", description: "Vaccine và chế phẩm sinh học cần được tư vấn phù hợp." },
  { id: "cat-nutrition", name: "Vitamin và dinh dưỡng", slug: "vitamin-dinh-duong", kind: "product_type", description: "Vitamin, khoáng và sản phẩm bổ sung dinh dưỡng." },
  { id: "cat-hygiene", name: "Sát trùng và vệ sinh", slug: "sat-trung-ve-sinh", kind: "product_type", description: "Giải pháp vệ sinh dụng cụ và khu vực chăn nuôi." },
  { id: "cat-supplies", name: "Dụng cụ thú y", slug: "dung-cu-thu-y", kind: "product_type", description: "Dụng cụ và vật tư phục vụ chăm sóc thú y." },
  { id: "need-antibiotic", name: "Kháng sinh", slug: "khang-sinh", kind: "treatment_need", description: "Tra cứu nhóm kháng sinh thú y theo vật nuôi và dạng sản phẩm." },
  { id: "need-vitamin", name: "Vitamin và khoáng", slug: "vitamin-khoang-chat", kind: "treatment_need", description: "Vitamin, khoáng chất và sản phẩm bổ sung dinh dưỡng." },
  { id: "need-digestive", name: "Hỗ trợ tiêu hóa", slug: "ho-tro-tieu-hoa", kind: "treatment_need", description: "Tìm sản phẩm theo nhu cầu tiêu hóa và dinh dưỡng." },
  { id: "need-respiratory", name: "Hỗ trợ hô hấp", slug: "ho-tro-ho-hap", kind: "treatment_need", description: "Tra cứu nhóm sản phẩm hỗ trợ đường hô hấp." },
  { id: "need-disinfection", name: "Sát trùng", slug: "sat-trung", kind: "treatment_need", description: "Dung dịch vệ sinh và sát trùng khu vực chăn nuôi." },
  { id: "need-vaccine", name: "Vaccine", slug: "vaccine", kind: "treatment_need", description: "Vaccine và sinh phẩm cần xác nhận bảo quản, quy cách." },
  { id: "need-parasite", name: "Kiểm soát ký sinh trùng", slug: "kiem-soat-ky-sinh-trung", kind: "treatment_need", description: "Nhóm sản phẩm cần lựa chọn theo loài và hướng dẫn chuyên môn." },
  { id: "need-tools", name: "Dụng cụ thú y", slug: "dung-cu", kind: "treatment_need", description: "Bơm tiêm, dụng cụ khám và vật tư chăm sóc thú y." },
  { id: "need-recovery", name: "Điện giải và phục hồi", slug: "dien-giai-phuc-hoi", kind: "treatment_need", description: "Sản phẩm bổ sung điện giải và hỗ trợ phục hồi." },
];

export const brands: Brand[] = [
  { id: "brand-vet68-demo", name: "Vet68 Demo", slug: "vet68-demo", description: "Nhãn dữ liệu minh họa, không phải thương hiệu sản phẩm đang kinh doanh.", logo: "/brand/demo/vet68-demo.svg" },
  { id: "brand-anivita-demo", name: "AniVita Demo", slug: "anivita-demo", description: "Thương hiệu minh họa dùng để kiểm thử catalogue.", logo: "/brand/demo/anivita-demo.svg" },
  { id: "brand-farmcare-demo", name: "FarmCare Demo", slug: "farmcare-demo", description: "Thương hiệu minh họa dùng để kiểm thử bộ lọc.", logo: "/brand/demo/farmcare-demo.svg" },
  { id: "brand-biovet-demo", name: "BioVet Demo", slug: "biovet-demo", description: "Thương hiệu minh họa cho vaccine và sinh phẩm.", logo: "/brand/demo/biovet-demo.svg" },
];

const category = (slug: string) => categories.find((item) => item.slug === slug)!;
const animal = (slug: string) => animalTypes.find((item) => item.slug === slug)!;
const brand = (slug: string) => brands.find((item) => item.slug === slug)!;

const demoNotice = "Dữ liệu sản phẩm minh họa. Nội dung chuyên môn, chỉ định và hướng dẫn sử dụng đang chờ Vet Medicine 68 xác minh trước khi xuất bản chính thức.";

export const products: Product[] = [
  {
    id: "product-001",
    name: "Amoxicillin 50% Demo",
    slug: "amoxicillin-50-demo",
    sku: "VET68-001",
    shortDescription: "Sản phẩm mẫu dùng để minh họa catalogue thuốc thú y và trạng thái giá cố định.",
    description: demoNotice,
    brand: brand("vet68-demo"),
    category: category("thuoc-thu-y"),
    secondaryCategories: [category("khang-sinh"), category("ho-tro-ho-hap")],
    animals: [animal("gia-suc"), animal("gia-cam")],
    referencePrice: 125000,
    priceDisplayMode: "fixed",
    priceNote: "Giá tham khảo cho dữ liệu demo.",
    unit: "Gói",
    dosageForm: "Bột",
    activeIngredients: "Thông tin minh họa: Amoxicillin 50%.",
    packaging: "Gói 100 g",
    indications: demoNotice,
    usageInformation: "Không có hướng dẫn liều dùng trong dữ liệu demo. Vui lòng tham khảo nhãn sản phẩm và tư vấn chuyên môn.",
    safetyInformation: "Không tự sử dụng dữ liệu demo để điều trị. Đọc kỹ nhãn và thông tin từ nhà sản xuất.",
    requiresConsultation: true,
    isFeatured: true,
    isNew: false,
    isActive: true,
    images: [{ src: "/images/products/demo-antibiotic-sachet.svg", alt: "Minh hoạ gói bột kháng sinh thú y demo" }],
    updatedAt: "2026-07-20",
  },
  {
    id: "product-002",
    name: "Vitamin ADE Plus Demo",
    slug: "vitamin-ade-plus-demo",
    sku: "VET68-002",
    shortDescription: "Sản phẩm mẫu minh họa nhóm vitamin và giá tham khảo khoảng.",
    description: demoNotice,
    brand: brand("anivita-demo"),
    category: category("vitamin-dinh-duong"),
    secondaryCategories: [category("vitamin-khoang-chat"), category("dien-giai-phuc-hoi")],
    animals: [animal("gia-suc"), animal("gia-cam")],
    referencePrice: 98000,
    priceDisplayMode: "approximate",
    priceNote: "Mức giá minh họa có thể thay đổi theo quy cách và thời điểm.",
    unit: "Chai",
    dosageForm: "Dung dịch",
    activeIngredients: "Thông tin thành phần đang chờ xác minh.",
    packaging: "Chai 100 ml",
    indications: demoNotice,
    usageInformation: "Liên hệ Vet68 để được kiểm tra đúng sản phẩm và quy cách.",
    safetyInformation: "Thông tin website không thay thế hướng dẫn từ bác sĩ thú y hoặc nhà sản xuất.",
    requiresConsultation: false,
    isFeatured: true,
    isNew: true,
    isActive: true,
    images: [{ src: "/images/products/demo-vitamin-bottle.svg", alt: "Minh hoạ chai vitamin thú y demo" }],
    updatedAt: "2026-07-22",
  },
  {
    id: "product-003",
    name: "Vaccine Newcastle Demo",
    slug: "vaccine-newcastle-demo",
    sku: "VET68-003",
    shortDescription: "Sản phẩm mẫu minh họa trạng thái liên hệ báo giá và yêu cầu tư vấn.",
    description: demoNotice,
    brand: brand("biovet-demo"),
    category: category("vaccine-sinh-pham"),
    secondaryCategories: [category("vaccine")],
    animals: [animal("gia-cam")],
    referencePrice: null,
    priceDisplayMode: "contact",
    priceNote: "Liên hệ để kiểm tra quy cách, bảo quản và tình trạng cung ứng.",
    unit: "Lọ",
    dosageForm: "Sinh phẩm",
    activeIngredients: "Thông tin chủng và hàm lượng đang chờ nhà cung cấp xác minh.",
    packaging: "Quy cách theo nhà sản xuất",
    indications: demoNotice,
    usageInformation: "Vaccine cần được lựa chọn, bảo quản và sử dụng theo hướng dẫn chuyên môn đã xác minh.",
    safetyInformation: "Không sử dụng thông tin demo để xây dựng lịch vaccine.",
    requiresConsultation: true,
    isFeatured: true,
    isNew: true,
    isActive: true,
    images: [{ src: "/images/products/demo-vaccine-vials.svg", alt: "Minh hoạ các lọ vaccine thú y demo" }],
    updatedAt: "2026-07-23",
  },
  {
    id: "product-004",
    name: "Iodine Disinfectant Demo",
    slug: "iodine-disinfectant-demo",
    sku: "VET68-004",
    shortDescription: "Dữ liệu mẫu cho nhóm sát trùng và vệ sinh khu vực chăn nuôi.",
    description: demoNotice,
    brand: brand("farmcare-demo"),
    category: category("sat-trung-ve-sinh"),
    secondaryCategories: [category("sat-trung")],
    animals: [animal("gia-suc"), animal("gia-cam")],
    referencePrice: 165000,
    priceDisplayMode: "fixed",
    priceNote: "Giá tham khảo demo.",
    unit: "Chai",
    dosageForm: "Dung dịch sát trùng",
    activeIngredients: "Thông tin nồng độ đang chờ xác minh.",
    packaging: "Chai 1 lít",
    indications: demoNotice,
    usageInformation: "Tỷ lệ pha và phạm vi sử dụng phải lấy từ nhãn sản phẩm đã xác minh.",
    safetyInformation: "Không trộn hóa chất khi chưa có hướng dẫn an toàn phù hợp.",
    requiresConsultation: false,
    isFeatured: true,
    isNew: true,
    isActive: true,
    images: [{ src: "/images/products/demo-disinfectant.svg", alt: "Minh hoạ can dung dịch sát trùng thú y demo" }],
    updatedAt: "2026-07-24",
  },
  {
    id: "product-005",
    name: "Calcium Mineral Mix Demo",
    slug: "calcium-mineral-mix-demo",
    sku: "VET68-005",
    shortDescription: "Sản phẩm mẫu cho nhóm khoáng và dinh dưỡng bổ sung.",
    description: demoNotice,
    brand: brand("anivita-demo"),
    category: category("vitamin-dinh-duong"),
    secondaryCategories: [category("dien-giai-phuc-hoi")],
    animals: [animal("gia-suc")],
    referencePrice: 210000,
    priceDisplayMode: "approximate",
    priceNote: "Giá khoảng cho dữ liệu demo, chưa phải báo giá bán hàng.",
    unit: "Túi",
    dosageForm: "Bột trộn",
    activeIngredients: "Danh sách khoáng chất đang chờ xác minh.",
    packaging: "Túi 1 kg",
    indications: demoNotice,
    usageInformation: "Khẩu phần sử dụng phải do đơn vị chuyên môn hoặc nhà sản xuất cung cấp.",
    safetyInformation: "Không thay đổi khẩu phần vật nuôi chỉ dựa trên nội dung demo.",
    requiresConsultation: false,
    isFeatured: false,
    isNew: true,
    isActive: true,
    images: [{ src: "/images/products/demo-mineral-bag.svg", alt: "Minh hoạ túi khoáng dinh dưỡng thú y demo" }],
    updatedAt: "2026-07-25",
  },
  {
    id: "product-006",
    name: "Bơm tiêm thú y 20 ml Demo",
    slug: "bom-tiem-thu-y-20ml-demo",
    sku: "VET68-006",
    shortDescription: "Dụng cụ mẫu để kiểm thử catalogue vật tư thú y.",
    description: demoNotice,
    brand: brand("farmcare-demo"),
    category: category("dung-cu-thu-y"),
    secondaryCategories: [category("dung-cu")],
    animals: [animal("gia-suc")],
    referencePrice: 45000,
    priceDisplayMode: "fixed",
    priceNote: "Giá tham khảo demo theo một đơn vị.",
    unit: "Cái",
    dosageForm: "Dụng cụ",
    activeIngredients: "Không áp dụng.",
    packaging: "1 cái",
    indications: "Dụng cụ minh họa. Thông số kỹ thuật đang chờ xác minh.",
    usageInformation: "Sử dụng theo hướng dẫn của nhà sản xuất và quy trình chuyên môn.",
    safetyInformation: "Bảo đảm vệ sinh và xử lý dụng cụ theo quy định phù hợp.",
    requiresConsultation: false,
    isFeatured: false,
    isNew: false,
    isActive: true,
    images: [{ src: "/images/products/demo-veterinary-syringe.svg", alt: "Minh hoạ bơm tiêm định lượng thú y demo" }],
    updatedAt: "2026-07-18",
  },
];

export const posts: Post[] = [
  {
    id: "post-001",
    title: "Cách đọc thông tin trên nhãn thuốc thú y",
    slug: "cach-doc-thong-tin-tren-nhan-thuoc-thu-y",
    excerpt: "Các mục cần kiểm tra trên nhãn trước khi trao đổi với nhà cung cấp hoặc bác sĩ thú y.",
    content: "## Nội dung minh họa\n\nBài viết đang dùng dữ liệu demo. Khi xuất bản chính thức, nội dung phải được Vet Medicine 68 kiểm tra nguồn và người duyệt chuyên môn.\n\n### Các thông tin nên ghi lại\n\n- Tên đầy đủ của sản phẩm\n- Nhà sản xuất và số lô\n- Thành phần được ghi trên nhãn\n- Quy cách đóng gói\n- Điều kiện bảo quản\n- Hạn sử dụng\n\nThông tin trên website chỉ mang tính tham khảo và không thay thế tư vấn của bác sĩ thú y hoặc hướng dẫn từ nhà sản xuất.",
    coverImage: "/images/products/demo-antibiotic-sachet.svg",
    coverAlt: "Minh hoạ bao bì sản phẩm thú y dùng cho bài viết demo",
    publishedAt: "2026-07-24",
    readingMinutes: 4,
  },
  {
    id: "post-002",
    title: "Chuẩn bị thông tin gì khi cần tư vấn sản phẩm",
    slug: "chuan-bi-thong-tin-khi-can-tu-van-san-pham",
    excerpt: "Một danh sách ngắn giúp cuộc trao đổi qua Zalo hoặc điện thoại rõ ràng và hữu ích hơn.",
    content: "## Nội dung minh họa\n\nHãy chuẩn bị tên vật nuôi, độ tuổi hoặc giai đoạn chăn nuôi, tên sản phẩm đang quan tâm, SKU và hình ảnh nhãn nếu có.\n\nKhông gửi hoặc áp dụng phác đồ điều trị chưa được người có chuyên môn xác minh.",
    coverImage: "/images/home/hero-veterinary-products.jpg",
    coverAlt: "Chó đeo ống nghe, hình minh hoạ cho tư vấn thú y",
    publishedAt: "2026-07-22",
    readingMinutes: 3,
  },
  {
    id: "post-003",
    title: "Bảo quản sản phẩm thú y: những điểm cần xác minh",
    slug: "bao-quan-san-pham-thu-y-nhung-diem-can-xac-minh",
    excerpt: "Nhiệt độ, ánh sáng, bao bì và thời gian sau mở nắp cần được lấy từ nguồn chính thức.",
    content: "## Nội dung minh họa\n\nMỗi sản phẩm có yêu cầu bảo quản khác nhau. Chỉ sử dụng điều kiện bảo quản được ghi trên nhãn hoặc tài liệu chính thức của nhà sản xuất.\n\nĐối với vaccine và sinh phẩm, hãy liên hệ đơn vị cung cấp để xác minh yêu cầu vận chuyển và bảo quản trước khi đặt hàng.",
    coverImage: "/images/demo/article-care.jpg",
    coverAlt: "Người chăm sóc mèo, hình minh họa cho bài viết kiến thức thú y",
    publishedAt: "2026-07-20",
    readingMinutes: 4,
  },
];
