export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type CategoryInsert = { id?: string; parent_id?: string | null; name: string; slug: string; kind?: "product_type" | "treatment_need"; description?: string | null; image_path?: string | null; image_alt?: string | null; is_active?: boolean; sort_order?: number; seo_title?: string | null; seo_description?: string | null; created_at?: string; updated_at?: string };
type AnimalTypeInsert = { id?: string; name: string; slug: string; description?: string | null; image_path?: string | null; image_alt?: string | null; is_active?: boolean; sort_order?: number; seo_title?: string | null; seo_description?: string | null; created_at?: string; updated_at?: string };
type BrandInsert = { id?: string; name: string; slug: string; description?: string | null; logo_path?: string | null; logo_alt?: string | null; website_url?: string | null; is_active?: boolean; sort_order?: number; seo_title?: string | null; seo_description?: string | null; created_at?: string; updated_at?: string };
type ProductInsert = { id?: string; name: string; slug: string; sku: string; short_description?: string | null; description?: string | null; brand_id?: string | null; category_id?: string | null; reference_price?: number | null; price_display_mode?: "fixed" | "approximate" | "contact" | null; price_note?: string | null; unit?: string | null; dosage_form?: string | null; active_ingredients?: string | null; packaging?: string | null; indications?: string | null; usage_information?: string | null; safety_information?: string | null; requires_consultation?: boolean; is_featured?: boolean; is_new?: boolean; is_active?: boolean; seo_title?: string | null; seo_description?: string | null; published_at?: string | null; created_at?: string; updated_at?: string };
type ProductImageInsert = { id?: string; product_id: string; storage_path: string; alt_text: string; sort_order?: number; is_primary?: boolean; created_at?: string };
type PostInsert = { id?: string; author_id?: string | null; title: string; slug: string; excerpt?: string | null; content_markdown?: string; cover_path?: string | null; cover_alt?: string | null; status?: "draft" | "published"; seo_title?: string | null; seo_description?: string | null; published_at?: string | null; created_at?: string; updated_at?: string };
type BannerInsert = { id?: string; title: string; subtitle?: string | null; placement: "home_hero" | "home_promotion" | "promotions_page"; desktop_image_path: string; mobile_image_path?: string | null; image_alt: string; link_url?: string | null; is_active?: boolean; sort_order?: number; starts_at?: string | null; ends_at?: string | null; created_at?: string; updated_at?: string };
type SiteSettingInsert = { key: string; value?: Json; is_public?: boolean; updated_by?: string | null; updated_at?: string };

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string | null; role: "staff" | "admin"; is_active: boolean; created_at: string; updated_at: string }; Insert: { id: string; full_name?: string | null; role?: "staff" | "admin"; is_active?: boolean }; Update: { full_name?: string | null; role?: "staff" | "admin"; is_active?: boolean }; Relationships: [] };
      categories: { Row: { id: string; parent_id: string | null; name: string; slug: string; kind: "product_type" | "treatment_need"; description: string | null; image_path: string | null; image_alt: string | null; is_active: boolean; sort_order: number; seo_title: string | null; seo_description: string | null; created_at: string; updated_at: string }; Insert: CategoryInsert; Update: Partial<CategoryInsert>; Relationships: [] };
      animal_types: { Row: { id: string; name: string; slug: string; description: string | null; image_path: string | null; image_alt: string | null; is_active: boolean; sort_order: number; seo_title: string | null; seo_description: string | null; created_at: string; updated_at: string }; Insert: AnimalTypeInsert; Update: Partial<AnimalTypeInsert>; Relationships: [] };
      brands: { Row: { id: string; name: string; slug: string; description: string | null; logo_path: string | null; logo_alt: string | null; website_url: string | null; is_active: boolean; sort_order: number; seo_title: string | null; seo_description: string | null; created_at: string; updated_at: string }; Insert: BrandInsert; Update: Partial<BrandInsert>; Relationships: [] };
      products: { Row: { id: string; name: string; slug: string; sku: string; short_description: string | null; description: string | null; brand_id: string | null; category_id: string | null; reference_price: number | null; price_display_mode: "fixed" | "approximate" | "contact" | null; price_note: string | null; unit: string | null; dosage_form: string | null; active_ingredients: string | null; packaging: string | null; indications: string | null; usage_information: string | null; safety_information: string | null; requires_consultation: boolean; is_featured: boolean; is_new: boolean; is_active: boolean; seo_title: string | null; seo_description: string | null; published_at: string | null; created_at: string; updated_at: string }; Insert: ProductInsert; Update: Partial<ProductInsert>; Relationships: [] };
      product_categories: { Row: { product_id: string; category_id: string; created_at: string }; Insert: { product_id: string; category_id: string }; Update: never; Relationships: [] };
      product_animal_types: { Row: { product_id: string; animal_type_id: string; created_at: string }; Insert: { product_id: string; animal_type_id: string }; Update: never; Relationships: [] };
      product_images: { Row: { id: string; product_id: string; storage_path: string; alt_text: string; sort_order: number; is_primary: boolean; created_at: string }; Insert: ProductImageInsert; Update: Partial<ProductImageInsert>; Relationships: [] };
      posts: { Row: { id: string; author_id: string | null; title: string; slug: string; excerpt: string | null; content_markdown: string; cover_path: string | null; cover_alt: string | null; status: "draft" | "published"; seo_title: string | null; seo_description: string | null; published_at: string | null; created_at: string; updated_at: string }; Insert: PostInsert; Update: Partial<PostInsert>; Relationships: [] };
      banners: { Row: { id: string; title: string; subtitle: string | null; placement: "home_hero" | "home_promotion" | "promotions_page"; desktop_image_path: string; mobile_image_path: string | null; image_alt: string; link_url: string | null; is_active: boolean; sort_order: number; starts_at: string | null; ends_at: string | null; created_at: string; updated_at: string }; Insert: BannerInsert; Update: Partial<BannerInsert>; Relationships: [] };
      site_settings: { Row: { key: string; value: Json; is_public: boolean; updated_by: string | null; updated_at: string }; Insert: SiteSettingInsert; Update: Partial<SiteSettingInsert>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: { current_staff_role: { Args: Record<string, never>; Returns: "staff" | "admin" | null }; is_staff: { Args: Record<string, never>; Returns: boolean }; is_admin: { Args: Record<string, never>; Returns: boolean }; search_catalogue_product_ids: { Args: { search_query: string }; Returns: Array<{ product_id: string; search_rank: number }> } };
    Enums: { staff_role: "staff" | "admin"; category_kind: "product_type" | "treatment_need"; price_display_mode: "fixed" | "approximate" | "contact"; post_status: "draft" | "published"; banner_placement: "home_hero" | "home_promotion" | "promotions_page" };
    CompositeTypes: Record<string, never>;
  };
};
