import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { BadgeCheck, BookOpenCheck, MessageCircle, SearchCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = { title: "Giới thiệu", description: "Vet Medicine 68 xây dựng catalogue sản phẩm thú y rõ ràng, dễ tìm và tập trung vào tư vấn trực tiếp.", alternates: { canonical: "/gioi-thieu" } };

export default function AboutPage() {
  return <><section className="border-b border-border bg-white"><div className="site-container grid gap-10 py-12 md:grid-cols-[0.9fr_1.1fr] md:items-center md:py-16"><div><h1 className="text-4xl font-bold tracking-[-0.04em] text-primary md:text-6xl">Catalogue rõ ràng cho quyết định cần thận trọng</h1><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">Vet Medicine 68 giúp khách hàng tìm sản phẩm, kiểm tra thông tin cơ bản và liên hệ trực tiếp trước khi đặt hàng.</p><Button className="action-button mt-7 h-11 px-5" size="lg" asChild><Link href="/lien-he"><MessageCircle aria-hidden="true" /> Liên hệ Vet68</Link></Button></div><div className="relative aspect-[4/3] overflow-hidden rounded-2xl bg-soft-blue retail-card-shadow"><Image src="/images/home/hero-veterinary-products.jpg" alt="Chó đeo ống nghe, hình minh hoạ cho hoạt động tư vấn thú y" fill priority sizes="(max-width: 768px) 100vw, 55vw" className="object-cover" /></div></div></section><section className="site-container section-space"><div className="max-w-3xl"><h2 className="text-3xl font-bold text-primary md:text-4xl">Cách Vet68 định hướng website</h2><p className="mt-4 leading-7 text-muted-foreground">Website không cố thay thế bác sĩ thú y, nhà sản xuất hoặc cuộc trao đổi trực tiếp. Mục tiêu là giảm nhầm lẫn khi tìm kiếm và liên hệ.</p></div><div className="mt-9 grid gap-6 md:grid-cols-2">{[[SearchCheck,"Dễ tìm sản phẩm","Tên, SKU, thương hiệu, danh mục và vật nuôi được tổ chức thành các đường tìm kiếm rõ ràng."],[BadgeCheck,"Giá được ghi đúng trạng thái","Giá cố định, giá khoảng và liên hệ báo giá không bị trộn lẫn hoặc thay bằng số 0."],[BookOpenCheck,"Nội dung có giới hạn","Thông tin chuyên môn chỉ được xuất bản khi có nguồn do đơn vị kinh doanh xác minh."],[MessageCircle,"Liên hệ là bước chính","Zalo và điện thoại là phương thức để xác nhận giá, quy cách và cách đặt hàng."]].map(([Icon,title,body]) => <div key={String(title)} className="flex gap-4 rounded-2xl border border-border bg-white p-5"><Icon className="mt-1 size-6 shrink-0 text-primary" aria-hidden="true" /><div><h3 className="text-xl font-bold">{String(title)}</h3><p className="mt-2 leading-7 text-muted-foreground">{String(body)}</p></div></div>)}</div></section></>;
}
